---
title: "Scenarios"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{"Scenarios"}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Scenarios

```{r setup}
library(keys.lid)
scenarios <- keys.lid::read_scenarios()

DT::datatable(scenarios)

```
## Simulate Performance

```{r simulate_performances, eval = FALSE}

### Bioretention Cell
br <- keys.lid::simulate_performances(
  lid_selected = scenarios[scenarios$lid_name_tidy == "bioretention_cell",],
  lid_area_fractions = c(0, 0.05, 0.1, 0.2)
  )

### Green Roof
if(FALSE) {
### not yet working
gr <- keys.lid::simulate_performances(
  lid_selected = scenarios[scenarios$lid_name_tidy == "green_roof",],
  lid_area_fractions = c(0, 1)
  )
}
### "permeable_pavement"
pp <- keys.lid::simulate_performances(
  lid_selected = scenarios[scenarios$lid_name_tidy == "permeable_pavement",],
  lid_area_fractions = c(0, 1)
  )

performances <- dplyr::bind_rows(br, pp)
```


